/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_config"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/game": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_game"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_player_games"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_pvp_game"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}/transcript": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_pvp_transcript"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/guess": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_guess"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_leaderboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/leaderboard/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_daily_leaderboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ContractConfig: {
            /** @description Per-player stake (wei, as a decimal string) for `escrow.join`. */
            amount?: string | null;
            /**
             * Format: int32
             * @description Number of players per PvP game (the escrow lobby capacity).
             */
            capacity?: number | null;
            commitmentAddress: string;
            escrowAddress?: string | null;
            pvpEnabled: boolean;
            resolver: string;
            statsAddress?: string | null;
            /**
             * Format: int32
             * @description Per-player play window before a forced timeout, in seconds.
             */
            timeoutSecs?: number | null;
            /** @description Circles token a player must stake to join a PvP game. */
            token?: string | null;
        };
        DailyResult: {
            address: string;
            /** Format: int32 */
            guesses: number;
            solved: boolean;
        };
        ErrorResponse: {
            error: string;
        };
        GameResponse: {
            /**
             * @description The day's answer, only revealed once the player's game is over (won or
             *     lost). Withheld while they're still playing.
             */
            answer?: string | null;
            /** Format: int32 */
            gameId: number;
            /**
             * @description Player's recorded guesses for this game, in order. Only populated when
             *     `?player=` is provided. An empty vec means the player hasn't guessed yet.
             */
            guesses?: components["schemas"]["PlayerGuess"][] | null;
            /**
             * @description "playing" | "won" | "lost" derived from `guesses`. Only set when
             *     `?player=` is provided.
             */
            status?: string | null;
        };
        GuessRequest: {
            gameId: string;
            guess: string;
            /** Format: int32 */
            guessNumber: number;
            player?: string | null;
        };
        GuessResponse: {
            answer?: string | null;
            gameOver: boolean;
            guess: string;
            results: components["schemas"]["LetterResult"][];
            won: boolean;
        };
        LeaderboardEntry: {
            address: string;
            /** Format: double */
            avg_guesses: number;
            /** Format: int32 */
            games_played: number;
            /** Format: int32 */
            wins: number;
        };
        /** @enum {string} */
        LetterResult: "correct" | "present" | "absent";
        PlayerGuess: {
            results: components["schemas"]["LetterResult"][];
            word: string;
        };
        PvpGameResponse: {
            answer?: string | null;
            /** Format: int32 */
            capacity: number;
            gameId: string;
            gameType: string;
            players: components["schemas"]["PvpPlayerStatus"][];
            status: string;
            /** Format: int32 */
            timeoutSecs: number;
        };
        PvpPlayerStatus: {
            address: string;
            /** Format: int32 */
            guessCount: number;
            status: string;
        };
        PvpTranscript: {
            answer: string;
            gameId: string;
            players: components["schemas"]["PvpTranscriptPlayer"][];
            status: string;
        };
        PvpTranscriptGuess: {
            results: components["schemas"]["LetterResult"][];
            word: string;
        };
        PvpTranscriptPlayer: {
            address: string;
            /** Format: int32 */
            guessCount: number;
            guesses: components["schemas"]["PvpTranscriptGuess"][];
            solved: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Contract configuration */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractConfig"];
                };
            };
            /** @description Resolver not configured */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_game: {
        parameters: {
            query?: {
                /**
                 * @description 0x-prefixed player address. When provided, the response includes the
                 *     player's recorded guesses so a client with no local state can rehydrate.
                 */
                player?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current daily game */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameResponse"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_player_games: {
        parameters: {
            query: {
                /** @description Player address (0x-prefixed) to look up PvP games for. */
                player: string;
                /** @description Limit to games still in progress (waiting/active). */
                active?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description PvP games for a player, most recent first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PvpGameResponse"][];
                };
            };
            /** @description Invalid player address */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_pvp_game: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description PvP game ID */
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description PvP game state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PvpGameResponse"];
                };
            };
            /** @description Game not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_pvp_transcript: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description PvP game ID */
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Both players' guess transcripts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PvpTranscript"];
                };
            };
            /** @description Game not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Game not settled yet */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    post_guess: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GuessRequest"];
            };
        };
        responses: {
            /** @description Guess evaluation result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuessResponse"];
                };
            };
            /** @description Invalid guess */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_leaderboard: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Leaderboard entries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaderboardEntry"][];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_daily_leaderboard: {
        parameters: {
            query: {
                gameId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daily game results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyResult"][];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Health check */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
}
