/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_config"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/game": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_game"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_player_games"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_pvp_game"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}/transcript": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_pvp_transcript"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/group/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_group_join"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/guess": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_guess"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_leaderboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/leaderboard/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_daily_leaderboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ContractConfig: {
            commitmentAddress: string;
            escrowAddress?: string | null;
            /**
             * @description Configured PvP lobbies (one per supported group). The frontend shows the
             *     ones the player is a group member of; each lobby's `botFunded` flag drives
             *     a "no bot backstop" warning rather than hiding the lobby.
             */
            lobbies: components["schemas"]["LobbyConfig"][];
            pvpEnabled: boolean;
            resolver: string;
            statsAddress?: string | null;
            /**
             * Format: int32
             * @description Per-player play window before a forced timeout, in seconds.
             */
            timeoutSecs?: number | null;
        };
        DailyResult: {
            address: string;
            /** Format: int32 */
            guesses: number;
            solved: boolean;
        };
        ErrorResponse: {
            error: string;
        };
        GameResponse: {
            /**
             * @description The day's answer, only revealed once the player's game is over (won or
             *     lost). Withheld while they're still playing.
             */
            answer?: string | null;
            /** Format: int32 */
            gameId: number;
            /**
             * @description Player's recorded guesses for this game, in order. Only populated when
             *     `?player=` is provided. An empty vec means the player hasn't guessed yet.
             */
            guesses?: components["schemas"]["PlayerGuess"][] | null;
            /**
             * @description "playing" | "won" | "lost" derived from `guesses`. Only set when
             *     `?player=` is provided.
             */
            status?: string | null;
        };
        GroupJoinRequest: {
            /** @description Player address (0x-prefixed) to onboard into the PvP group. */
            player: string;
            /**
             * @description Hex signature over [`group_join_message`] proving control of `player`
             *     (ECDSA for an EOA, or an ERC-1271 contract signature for a Safe avatar).
             */
            signature: string;
        };
        GroupJoinResponse: {
            /** @description True if they were already a member (no transaction was sent). */
            alreadyMember: boolean;
            /** @description True once the player is trusted by the group (newly or already). */
            joined: boolean;
        };
        GuessRequest: {
            gameId: string;
            guess: string;
            /** Format: int32 */
            guessNumber: number;
            player?: string | null;
        };
        GuessResponse: {
            answer?: string | null;
            gameOver: boolean;
            guess: string;
            results: components["schemas"]["LetterResult"][];
            won: boolean;
        };
        LeaderboardEntry: {
            address: string;
            /** Format: double */
            avg_guesses: number;
            /** Format: int32 */
            games_played: number;
            /** Format: int32 */
            wins: number;
        };
        /** @enum {string} */
        LetterResult: "correct" | "present" | "absent";
        /**
         * @description A single PvP lobby: one Circles group's wrapper token and stake. The escrow
         *     is group-agnostic, so each lobby is an independent `(resolver, token, amount,
         *     capacity)` bucket keyed on the wrapper token.
         */
        LobbyConfig: {
            /** @description Per-player stake (wei, as a decimal string) for `escrow.join`. */
            amount: string;
            /**
             * @description Live: the bot Safe holds ≥ 2× `amount` of `token` (headroom so two
             *     simultaneous joiners are both covered). Stamped per-request from shared
             *     state the bot refreshes each tick; `false` until the first tick.
             */
            botFunded: boolean;
            /**
             * Format: int32
             * @description Number of players per PvP game (the escrow lobby capacity).
             */
            capacity: number;
            /**
             * @description Group avatar address. Intersected with a player's Circles group
             *     memberships to decide whether the lobby is shown to them.
             */
            group: string;
            /** @description Human-readable group name, e.g. "Gnosis". */
            name: string;
            /** @description s-gCRC wrapper token a player stakes to join this lobby. */
            token: string;
        };
        PlayerGuess: {
            results: components["schemas"]["LetterResult"][];
            word: string;
        };
        PvpGameResponse: {
            answer?: string | null;
            /** Format: int32 */
            capacity: number;
            gameId: string;
            gameType: string;
            players: components["schemas"]["PvpPlayerStatus"][];
            status: string;
            /** Format: int32 */
            timeoutSecs: number;
        };
        PvpPlayerStatus: {
            address: string;
            /** Format: int32 */
            guessCount: number;
            status: string;
        };
        PvpTranscript: {
            answer: string;
            gameId: string;
            players: components["schemas"]["PvpTranscriptPlayer"][];
            status: string;
        };
        PvpTranscriptGuess: {
            results: components["schemas"]["LetterResult"][];
            word: string;
        };
        PvpTranscriptPlayer: {
            address: string;
            /** Format: int32 */
            guessCount: number;
            guesses: components["schemas"]["PvpTranscriptGuess"][];
            solved: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Contract configuration */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractConfig"];
                };
            };
            /** @description Resolver not configured */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_game: {
        parameters: {
            query?: {
                /**
                 * @description 0x-prefixed player address. When provided, the response includes the
                 *     player's recorded guesses so a client with no local state can rehydrate.
                 */
                player?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current daily game */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameResponse"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_player_games: {
        parameters: {
            query: {
                /** @description Player address (0x-prefixed) to look up PvP games for. */
                player: string;
                /** @description Limit to games still in progress (waiting/active). */
                active?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description PvP games for a player, most recent first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PvpGameResponse"][];
                };
            };
            /** @description Invalid player address */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_pvp_game: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description PvP game ID */
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description PvP game state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PvpGameResponse"];
                };
            };
            /** @description Game not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_pvp_transcript: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description PvP game ID */
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Both players' guess transcripts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PvpTranscript"];
                };
            };
            /** @description Game not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Game not settled yet */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    post_group_join: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GroupJoinRequest"];
            };
        };
        responses: {
            /** @description Player onboarded into the group */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupJoinResponse"];
                };
            };
            /** @description Invalid player address or signature */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Signature does not match player */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No recorded play for this address */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Trust transaction failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Group onboarding not configured */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    post_guess: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GuessRequest"];
            };
        };
        responses: {
            /** @description Guess evaluation result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuessResponse"];
                };
            };
            /** @description Invalid guess */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_leaderboard: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Leaderboard entries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaderboardEntry"][];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_daily_leaderboard: {
        parameters: {
            query: {
                gameId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daily game results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyResult"][];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Health check */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
}
