version: "3.8"

services:
  api:
    build:
      context: api
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      ARAK_DB_PATH: /data/arak.db
      RESOLVER_PRIVATE_KEY:
      RPC_URL: http://gnosis-erigon.dappnode:8545
      COMMITMENT_ADDRESS:
      STATS_ADDRESS:
    volumes:
      - data:/data
    ports:
      - "3001:3001"
    depends_on:
      - indexer

  indexer:
    image: ghcr.io/bh2smith/arak:main
    restart: unless-stopped
    entrypoint: ["/usr/bin/tini", "--"]
    command: ["/opt/arak/arak"]
    working_dir: /data
    volumes:
      - data:/data
      - ./arak.toml:/data/arak.toml:ro

volumes:
  data: {}
