// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "forge-std/Test.sol";
import {HonkVerifier} from "../../contracts/zk/WordleVerifier.sol";

/// @notice End-to-end ZK feasibility test for the Wordle-duel spike.
///         Loads a proof + public inputs generated by `bb` (see circuits/README.md)
///         and checks the generated UltraHonk Solidity verifier accepts a valid
///         proof and rejects a tampered one. Also captures verifier gas via the
///         gas report (`forge test --gas-report`) and bytecode size via
///         `forge build --sizes` (EIP-170 limit = 24576 bytes).
///
///         Artifacts are committed fixtures (so CI, which has no ZK toolchain,
///         can run this). They are a matched pair with the committed verifier;
///         regenerate both together via the commands in circuits/README.md.
///           test/zk/fixtures/proof          — UltraHonk (ZK, evm) proof
///           test/zk/fixtures/public_inputs  — 9 x 32-byte words:
///                  [commitment, dictionary_root, match_binding, guess[0..5], feedback]
contract WordleVerifierTest is Test {
    HonkVerifier internal verifier;

    // Number of *circuit* public inputs (the 8 pairing-point limbs live inside
    // the proof, not in this array).
    uint256 internal constant NUM_PUBLIC_INPUTS = 9;
    // Index of the packed feedback within the public inputs.
    uint256 internal constant FEEDBACK_INDEX = 8;

    string internal constant PROOF_PATH = "test/zk/fixtures/proof";
    string internal constant PUBLIC_INPUTS_PATH = "test/zk/fixtures/public_inputs";

    function setUp() public {
        verifier = new HonkVerifier();
    }

    function _loadPublicInputs() internal view returns (bytes32[] memory pi) {
        bytes memory raw = vm.readFileBinary(PUBLIC_INPUTS_PATH);
        require(raw.length == NUM_PUBLIC_INPUTS * 32, "unexpected public_inputs length");
        pi = new bytes32[](NUM_PUBLIC_INPUTS);
        for (uint256 i = 0; i < NUM_PUBLIC_INPUTS; i++) {
            bytes32 word;
            // raw[32*i .. 32*i+32] -> word (skip 32-byte length prefix)
            assembly {
                word := mload(add(add(raw, 0x20), mul(i, 0x20)))
            }
            pi[i] = word;
        }
    }

    /// A valid bb-generated proof verifies on-chain.
    function test_validProofVerifies() public view {
        bytes memory proof = vm.readFileBinary(PROOF_PATH);
        bytes32[] memory publicInputs = _loadPublicInputs();
        assertTrue(verifier.verify(proof, publicInputs), "valid proof should verify");
    }

    /// Sanity: the public inputs are the values we expect from Prover.toml.
    /// Layout: [commitment, dictionary_root, match_binding, guess[0..5], feedback].
    /// guess "crane" -> 2,17,0,13,4 ; feedback packed = 293 = 0x125.
    function test_publicInputsMatchExpected() public view {
        bytes32[] memory pi = _loadPublicInputs();
        assertEq(uint256(pi[2]), 0x1234567890abcdef, "match_binding");
        assertEq(uint256(pi[3]), 2, "guess[0]=c");
        assertEq(uint256(pi[4]), 17, "guess[1]=r");
        assertEq(uint256(pi[5]), 0, "guess[2]=a");
        assertEq(uint256(pi[6]), 13, "guess[3]=n");
        assertEq(uint256(pi[7]), 4, "guess[4]=e");
        assertEq(uint256(pi[FEEDBACK_INDEX]), 293, "feedback packed");
    }

    /// Tampering with a public input (claiming a different feedback) must fail.
    /// The verifier may either return false or revert — both count as rejection.
    function test_tamperedFeedbackRejected() public view {
        bytes memory proof = vm.readFileBinary(PROOF_PATH);
        bytes32[] memory publicInputs = _loadPublicInputs();
        publicInputs[FEEDBACK_INDEX] = bytes32(uint256(294)); // claim 294 instead of 293

        try verifier.verify(proof, publicInputs) returns (bool ok) {
            assertFalse(ok, "tampered feedback must not verify");
        } catch {
            // revert is an acceptable rejection
        }
    }

    /// Tampering with the proof bytes must fail.
    function test_tamperedProofRejected() public view {
        bytes memory proof = vm.readFileBinary(PROOF_PATH);
        bytes32[] memory publicInputs = _loadPublicInputs();
        proof[proof.length - 1] = bytes1(uint8(proof[proof.length - 1]) ^ 0x01);

        try verifier.verify(proof, publicInputs) returns (bool ok) {
            assertFalse(ok, "tampered proof must not verify");
        } catch {
            // revert is an acceptable rejection
        }
    }
}
